If you get a Exception in thread error, that is completely 
normal and the code should still function